apiVersion: v1
kind: Secret
metadata:
  name: account-secrets
  namespace: default
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password@mongo.default.svc.cluster.local:27017/test"
  MONGODB_DATABASE: "test"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-controller-headless.default.svc.cluster.local:9092"
  SR_URL: "schema-registry-headless.default.svc.cluster.local:8081"
  CREDENTIALS_SOURCE: "USER_INFO"
  SR_USER_INFO: "user:password"
